# Generated by Django 4.0.3 on 2023-06-10 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noviceAngler', '0002_article_author_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
