# Generated by Django 4.0.3 on 2023-06-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noviceAngler', '0003_article_modify_date_comment_modify_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='post'),
        ),
    ]
