# Generated by Django 4.0.3 on 2023-06-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noviceAngler', '0005_alter_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(max_length=20)),
                ('fishing', models.CharField(max_length=20)),
                ('locate', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
            ],
        ),
    ]
