# Generated by Django 4.2.1 on 2023-06-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noviceAngler', '0007_rename_time_usersubmission_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_name', models.CharField(max_length=32)),
                ('float_fishing', models.TextField(blank=True, null=True)),
                ('lure_fishing', models.TextField(blank=True, null=True)),
                ('onetwo_fishing', models.TextField(blank=True, null=True)),
                ('locations', models.TextField()),
                ('notices', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/%Y%m%d')),
                ('season', models.CharField(max_length=32)),
            ],
        ),
    ]
