# Generated by Django 4.2.1 on 2023-06-11 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noviceAngler', '0008_fish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fish',
            old_name='float_fishing',
            new_name='fishing_ways',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='lure_fishing',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='onetwo_fishing',
        ),
    ]
